export const SHIM_VERSION_HEADER = "// strnd auto-update hook";

export function generateHookShim(version: string): string {
  const lines = [
    `#!/usr/bin/env node`,
    `${SHIM_VERSION_HEADER} | strnd v${version}`,
    `// Regenerates .strand after git operations. Do not edit manually.`,
    `// Regenerated by \`npx strnd setup\``,
    ``,
    `import { execFileSync } from "child_process";`,
    `import { writeFileSync, unlinkSync } from "fs";`,
    ``,
    `const LOCK = ".strnd/.lock";`,
    ``,
    `// Lockfile: prevent concurrent regeneration (rapid commits, rebase)`,
    `try { writeFileSync(LOCK, String(process.pid), { flag: "wx" }); }`,
    `catch { process.exit(0); }`,
    ``,
    `try {`,
    `  execFileSync("npx", ["strnd", "generate", "--silent"], {`,
    `    timeout: 30000,`,
    `    stdio: "ignore",`,
    `    shell: true,`,
    `  });`,
    `} catch { /* silent failure — stale .strand beats broken commits */ }`,
    `finally { try { unlinkSync(LOCK); } catch {} }`,
    ``,
  ];
  return lines.join("\n");
}
